#ifndef _ALTERA_HPS_SOC_SYSTEM_H_
#define _ALTERA_HPS_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'mailbox_1', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_1_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_1_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_1_COMPONENT_NAME mailbox_1
#define MAILBOX_1_BASE 0x0
#define MAILBOX_1_SPAN 16
#define MAILBOX_1_END 0xf

/*
 * Macros for device 'mailbox_0', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_0_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_0_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_0_COMPONENT_NAME mailbox_0
#define MAILBOX_0_BASE 0x10
#define MAILBOX_0_SPAN 16
#define MAILBOX_0_END 0x1f

/*
 * Macros for device 'mutex_2', class 'altera_avalon_mutex'
 * The macros are prefixed with 'MUTEX_2_'.
 * The prefix is the slave descriptor.
 */
#define MUTEX_2_COMPONENT_TYPE altera_avalon_mutex
#define MUTEX_2_COMPONENT_NAME mutex_2
#define MUTEX_2_BASE 0x20
#define MUTEX_2_SPAN 8
#define MUTEX_2_END 0x27
#define MUTEX_2_OWNER_INIT 0
#define MUTEX_2_OWNER_WIDTH 16
#define MUTEX_2_VALUE_INIT 0
#define MUTEX_2_VALUE_WIDTH 16

/*
 * Macros for device 'mutex_1', class 'altera_avalon_mutex'
 * The macros are prefixed with 'MUTEX_1_'.
 * The prefix is the slave descriptor.
 */
#define MUTEX_1_COMPONENT_TYPE altera_avalon_mutex
#define MUTEX_1_COMPONENT_NAME mutex_1
#define MUTEX_1_BASE 0x28
#define MUTEX_1_SPAN 8
#define MUTEX_1_END 0x2f
#define MUTEX_1_OWNER_INIT 0
#define MUTEX_1_OWNER_WIDTH 16
#define MUTEX_1_VALUE_INIT 0
#define MUTEX_1_VALUE_WIDTH 16

/*
 * Macros for device 'mutex_0', class 'altera_avalon_mutex'
 * The macros are prefixed with 'MUTEX_0_'.
 * The prefix is the slave descriptor.
 */
#define MUTEX_0_COMPONENT_TYPE altera_avalon_mutex
#define MUTEX_0_COMPONENT_NAME mutex_0
#define MUTEX_0_BASE 0x30
#define MUTEX_0_SPAN 8
#define MUTEX_0_END 0x37
#define MUTEX_0_OWNER_INIT 0
#define MUTEX_0_OWNER_WIDTH 16
#define MUTEX_0_VALUE_INIT 0
#define MUTEX_0_VALUE_WIDTH 16


#endif /* _ALTERA_HPS_SOC_SYSTEM_H_ */
