#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
#mkdir -p /run/network

case "$1" in
  start)
	printf "Starting custom init script "
	ifconfig eth0 10.42.0.2 netmask 255.255.255.0
	python3 /root/server.py
	;;
  stop)
	printf "Stopping custom init script "
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
