#ifndef _ALTERA_HPS_SOC_SYSTEM_H_
#define _ALTERA_HPS_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'mailbox_2', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_2_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_2_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_2_COMPONENT_NAME mailbox_2
#define MAILBOX_2_BASE 0x0
#define MAILBOX_2_SPAN 16
#define MAILBOX_2_END 0xf

/*
 * Macros for device 'mailbox_0', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_0_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_0_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_0_COMPONENT_NAME mailbox_0
#define MAILBOX_0_BASE 0x10
#define MAILBOX_0_SPAN 16
#define MAILBOX_0_END 0x1f

/*
 * Macros for device 'mailbox_1', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_1_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_1_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_1_COMPONENT_NAME mailbox_1
#define MAILBOX_1_BASE 0x20
#define MAILBOX_1_SPAN 16
#define MAILBOX_1_END 0x2f

/*
 * Macros for device 'mailbox_3', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_3_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_3_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_3_COMPONENT_NAME mailbox_3
#define MAILBOX_3_BASE 0x30
#define MAILBOX_3_SPAN 16
#define MAILBOX_3_END 0x3f


#endif /* _ALTERA_HPS_SOC_SYSTEM_H_ */
